apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: sasisecret
  containers:
  - name: busybox
    image: busybox:latest
    command:
        - ls
        - "-l"
        - "/etc/secret-volume"
    volumeMounts:
      - name: secret-volume
        readOnly: true
        mountPath: "/etc/secret-volume"