apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ["sh", "-c", "echo Pod started; sleep 3600"]
    envFrom:
      - configMapRef:
          name: democm
